//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vela.RM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vela.RM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid archetypeid.
        /// </summary>
        internal static string InvalidArchetypeId {
            get {
                return ResourceManager.GetString("InvalidArchetypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch number is smaller than 1.
        /// </summary>
        internal static string InvalidBranchNumber {
            get {
                return ResourceManager.GetString("InvalidBranchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch version is smaller than 1.
        /// </summary>
        internal static string InvalidBranchVersion {
            get {
                return ResourceManager.GetString("InvalidBranchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid domain name.
        /// </summary>
        internal static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid ehr uri.
        /// </summary>
        internal static string InvalidEhrUri {
            get {
                return ResourceManager.GetString("InvalidEhrUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid guid.
        /// </summary>
        internal static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid objectversionid.
        /// </summary>
        internal static string InvalidObjectVersionId {
            get {
                return ResourceManager.GetString("InvalidObjectVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trunk version is smaller than 1.
        /// </summary>
        internal static string InvalidTrunkVersion {
            get {
                return ResourceManager.GetString("InvalidTrunkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid type for &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid versionid.
        /// </summary>
        internal static string InvalidVersionId {
            get {
                return ResourceManager.GetString("InvalidVersionId", resourceCulture);
            }
        }
    }
}
